import type { QuestionData } from '../types.js';

// Local question bank — used when the API is unavailable or the pool is empty.
// All questions are multiple_choice, in French, humor mandatory.
export const FALLBACK_QUESTIONS: QuestionData[] = [
  {
    question: "Tu joues à Space Invaders depuis 5 minutes et tu te fais déjà toucher. Quel est le nom du champion du monde de Space Invaders en 1980 ?",
    type: 'multiple_choice',
    choices: ['Toshiyuki Takahashi', 'Thierry La Fronde', 'Mario Bros', 'Toi (dans tes rêves)'],
    correct_answer: 'Toshiyuki Takahashi',
    humor_level: 'mild',
  },
  {
    question: "Un Pokémon frappe à ta porte à 3h du matin. Il veut de la tartiflette. Lequel est clairement le plus susceptible de faire ça ?",
    type: 'multiple_choice',
    choices: ['Ronflex (il avait faim)', 'Pikachu (insomniaque notoire)', 'Mewtwo (il est en crise existentielle)', 'Magicarpe (il saute partout, logique)'],
    correct_answer: 'Ronflex (il avait faim)',
    humor_level: 'absurd',
  },
  {
    question: "En France, le fromage c'est sacré — on en compte environ combien de variétés ?",
    type: 'multiple_choice',
    choices: ['Environ 1 000', 'Exactement 42', 'Environ 246', 'Plus de 5 000'],
    correct_answer: 'Environ 1 000',
    humor_level: 'mild',
  },
  {
    question: "Tu prends un penalty en finale de la Coupe du Monde. Le gardien a deviné ton côté. Qu'est-ce que tu fais ?",
    type: 'multiple_choice',
    choices: ['Tire quand même, au centre', 'Change de côté à la dernière seconde', 'Prétends être blessé', 'Passes la balle à ton pote'],
    correct_answer: 'Tire quand même, au centre',
    humor_level: 'mild',
  },
  {
    question: "Quelle est la capitale de la France ? (Oui, on commence facile, t'as failli crever quand même.)",
    type: 'multiple_choice',
    choices: ['Paris', 'Lyon', 'Marseille', 'Versailles'],
    correct_answer: 'Paris',
    humor_level: 'mild',
  },
  {
    question: "Dans les années 80, quel jeu d'arcade a popularisé les high scores publics et rendu les gens accros à gaspiller leurs pièces de 1 franc ?",
    type: 'multiple_choice',
    choices: ['Space Invaders', 'Pac-Man', 'Donkey Kong', 'Pong'],
    correct_answer: 'Space Invaders',
    humor_level: 'mild',
  },
  {
    question: "Scientifiquement, combien de temps peut-on regarder une pizza refroidir avant de craquer et de la manger ?",
    type: 'multiple_choice',
    choices: ['3 à 7 secondes', '30 secondes si t\'as de la volonté', 'Jamais, c\'est impossible', '2 minutes si t\'es stoïcien'],
    correct_answer: 'Jamais, c\'est impossible',
    humor_level: 'absurd',
  },
  {
    question: "Quel duo français a sorti l'album « Homework » en 1997 avec le tube « Around the World » ?",
    type: 'multiple_choice',
    choices: ['Daft Punk', 'Air', 'Justice', 'Phoenix'],
    correct_answer: 'Daft Punk',
    humor_level: 'mild',
  },
  {
    question: "Le « dab » est une célébration popularisée dans quel sport avant de contaminer le monde entier ?",
    type: 'multiple_choice',
    choices: ['Football américain', 'Basketball', 'Athlétisme', 'Pétanque professionnelle'],
    correct_answer: 'Football américain',
    humor_level: 'mild',
  },
  {
    question: "Si tu devais survivre une semaine avec UN seul aliment, lequel serait le plus sage nutritionnellement ?",
    type: 'multiple_choice',
    choices: ['Pommes de terre', 'Pizza', 'Barres chocolatées', 'Eau gazeuse'],
    correct_answer: 'Pommes de terre',
    humor_level: 'absurd',
  },
  {
    question: "Dans « Star Wars », quel personnage dit la réplique culte « Je suis ton père » ?",
    type: 'multiple_choice',
    choices: ['Dark Vador', 'Yoda', 'Obi-Wan Kenobi', 'R2-D2 (en bip)'],
    correct_answer: 'Dark Vador',
    humor_level: 'mild',
  },
  {
    question: "En musique, la note « Do » en anglais s'appelle comment ?",
    type: 'multiple_choice',
    choices: ['C', 'D', 'G', 'A'],
    correct_answer: 'C',
    humor_level: 'mild',
  },
  {
    question: "Tu croises Cristiano Ronaldo dans la rue. Il te dit « SIUUU ! ». Tu réponds quoi ?",
    type: 'multiple_choice',
    choices: ['SIUUU ! (réflexe pavlovien)', 'Rien, tu fais semblant de pas le reconnaître', 'Tu demandes un selfie pour Insta', 'Tu lui rappelles que Messi a plus de Ballons d\'Or'],
    correct_answer: 'SIUUU ! (réflexe pavlovien)',
    humor_level: 'absurd',
  },
  {
    question: "Quel pays a inventé le cinéma avec les frères Lumière ?",
    type: 'multiple_choice',
    choices: ['La France', 'Les États-Unis', 'L\'Angleterre', 'L\'Allemagne'],
    correct_answer: 'La France',
    humor_level: 'mild',
  },
  {
    question: "En informatique, combien font 2 puissance 10 ? (Aka la question que tout dev connaît en dormant)",
    type: 'multiple_choice',
    choices: ['1024', '1000', '2048', '512'],
    correct_answer: '1024',
    humor_level: 'mild',
  },
  {
    question: "La chaîne de restauration rapide française « Quick » a été rachetée et rebaptisée… quoi ?",
    type: 'multiple_choice',
    choices: ['Burger King', 'McDonald\'s', 'Five Guys', 'KFC'],
    correct_answer: 'Burger King',
    humor_level: 'mild',
  },
  {
    question: "Un alien débarque sur Terre et goûte un croissant au beurre parisien pour la première fois. Sa réaction est :",
    type: 'multiple_choice',
    choices: ['Il annule l\'invasion immédiatement', 'Il repart chercher sa famille', 'Il négocie un traité de paix contre la recette', 'Il pleure de joie et appelle sa maman alien'],
    correct_answer: 'Il annule l\'invasion immédiatement',
    humor_level: 'absurd',
  },
  {
    question: "Quel est le sport le plus regardé au monde ?",
    type: 'multiple_choice',
    choices: ['Football', 'Cricket', 'Basketball', 'Tennis'],
    correct_answer: 'Football',
    humor_level: 'mild',
  },
  {
    question: "Dans quel genre musical retrouve-t-on les artistes Daft Punk, David Guetta et Martin Garrix ?",
    type: 'multiple_choice',
    choices: ['Électro / EDM', 'Rock indé', 'Jazz fusion', 'Variété française de compét\''],
    correct_answer: 'Électro / EDM',
    humor_level: 'mild',
  },
  {
    question: "Combien y a-t-il de Pokémon dans la première génération ? (Celle qui compte vraiment selon les puristes.)",
    type: 'multiple_choice',
    choices: ['151', '152', '250', '386'],
    correct_answer: '151',
    humor_level: 'mild',
  },
];
